#!/bin/bash
#-- run from cron every minute

#-- retrieve mail
# awk could help here...
newIDs=`offlineimap -o | egrep "^Copy.*Remote:Inbox.*Local$" | cut -d" " -f3`

newCount=0
lastID=0
notifMsg=""

for id in $newIDs; do
    newCount=$(( $newCount + 1 ))
    lastID=id
    notifMsg=${notifMsg}`grabHeader`
done

#-- popup notification if new mail
if [ $newCount -ne 0 ]; then
    # do stuff with lastID
    notify-send -i ~/.mutt/mailIcon.png "${newCount} New"
fi
